---
title: "Notes and ToDo"
output: html_document
---

## To-Do

### Need to do

* Test that all ways of using/modifying the labs as described in the vignette works robustly.
* Test that all labs work, both locally and remote.

* Change labs such that each one only loads the 'iblir' package, no other packages. 
The iblir package in turn should list all required packages in the DESCRIPTION file.
DONE, NEEDS TO BE TESTED.

* Check all 3rd party materials (images/cartoons/data/etc.) to make sure it's allows re-use and could be included in a GPL or CC licensed package. 
* Remove additional Rmd file from labs 1 and 10.
* Further clean up all labs, remove any unused files. Possibly have all files for labs just in a single folder, e.g. just `www`? 
* Update logo


### Could do

* Add more features to deploy_labs, e.g. user can specify which account.
* Make it such that there is an app or page that can be deployed and easily points to all other labs. Should live on server inside main directory. E.g. we want server.com/iblir/ to load a page with links to all apps (if that is wanted, could be turned off).
* Figure out a way that for local deployment in which users just call one function which opens a graphical menu from which to choose labs. Probably same approach as above. E.g. a function called start_iblir() could do that as a wrapper around learnr::run_tutorial().
* write more testthat tests


## General Notes and Thoughts

* see the documentation.md file for general information

* Example of another R package consisting of learnR tutorials:
http://milton-the-cat.rocks/home/adventr.html




