---
title: "iblir Package Tutorial"
author: "<a href=http://handelgroup.uga.edu>Andreas Handel</a>"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{DSAIDE Package Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

``` {r, include = FALSE}
packagename = 'iblir'
```


## Summary

This document provides a brief introduction to the **Introductory Biostatistics Labs in R (iblir)** package.


## Getting Started

The package is not yet on CRAN, so you need to install it from GitHub as follows.

``` 
install.packages('remotes')
library('remotes')
install_github('andreashandel/iblir')
```

After the package is installed, you can load it

```
library('iblir')
```

To start the tutorials/labs, you type
```
run_tutorial('LabN', package = 'iblir')
```
where N is the lab number, e.g. `Lab1`, `Lab2`.

A startup message also tells you this.

The labs should open in your browser, and you can go through them.


## Lab Content


LAB 1: Introduction to the online lab format and Introduction to R and “Data”.  

LAB 2: Focuses on interpreting and making histograms in R. 
1.	Interpreting Histograms 
2.	Which variable types to use with histograms
3.	Making histograms 
4.	Impact of bin selection and 4 methods to help get the right size

LAB 3: Focuses on interpreting and making box plots in R
1.	Interpreting Box plots
2.	Making Box plots
3.	Comparing box plots

LAB 4: Introduces students to the steps of a basic data analysis
1.	Data Cleaning 
2.	Variable types in R
3.	Making Tables 
4.	Making Figures with numeric summaries

LAB 5: Life Tables
1.	Life expectancy 
2.	Survival Curves
3.	Hazard Functions

LAB 6: Diagnostic and Screening Tests
1.	Diagnostic and Screening tests
2.	Sensitivity, Specificity, and Accuracy
3.	ROC curves 
4.	AUC calculations
5.	Cut-off values

LAB 7: Discrete Distributions
1.	The Binomial Distribution
a.	Calculating Probability and Percentiles
2.	The Poisson Distribution
a.	Calculating Probability and Percentiles

LAB 8: Normal Distribution
1.	Calculating Probability and Percentiles

LAB 9: Random Sampling and Central Limit Theorem
1.	Review of distributions
a.	Setting to show that they can be approximated by normal distribution
2.	Random sampling
a.	So that getting good estimates with random samples does not require very large samples in many cases 
3.	Central Limit Theorem 
a.	Apply it to the data in the exercises and see if resulting distributions are normal

LAB 10: One Sample T Methods
1.	1-sample t-tests
a.	Hypothesis testing and Confidence Intervals
2.	Making new variables in R
a.	Using a variable in the data set to make a new one

LAB 11: Paired t Test
1.	Paired t-tests in R
a.	Hypothesis tests and Confidence Intervals
2.	Visualizing paired data in R

LAB 12: Two Sample t-test
1.	Two-sample t-test in R 
a.	Hypothesis tests and Confidence Intervals
2.	Violin Plots in R

LAB 13: Hypothesis Tests and Confidence Intervals for Proportions
1.	One Proportion tests in R
a.	Hypothesis tests and Confidence Intervals
2.	Two Proportion tests in R
a.	Hypothesis tests and Confidence Intervals



## Ways to use iblir

There are several ways the labs/the package can be used.


### Local

This is described above. Simply install and load the package. The greeting message will tell you how to load each lab. The Package website also provides this information.

### RStudio Cloud

This is basically the same as local, but students don't have to install `R` and `RStudio` and can instead do everything in their browser. 
To use it this way, set up a new RStudio Cloud project, install the `iblir` package (which will also install a ton of others). Then give students the link to the workspace. They log in, load the package and can use it as if they were running it locally.

Note that the free RStudio Cloud account might not be enough and you might need to upgrade to a paid account.

### You own Shiny server

Load the package, then run the `get_labs()` function. It will open a file browser and point you to a zip file with all the labs. Copy that zip file to your shiny server, ideally into its own folder (e.g. a folder called `iblir`). Then extract. You should end up with a folder for each lab, e.g. `/srv/shiny-server/iblir/Lab1`, `/srv/shiny-server/iblir/Lab2`, and so on. Make sure the `iblir` package is installed on your server. Also, make sure permissions for the folders are set correctly.

Once all is set up, students should be able to go to the Server/Lab URL to access each lab, e.g., by going to `shinyserver.myplace.edu/iblir/Lab1` and so on.

One option to run your own Shiny server is to use DigitalOcean and e.g. the [analogsea](https://pacha.dev/analogsea/) package.


### shinyapps.io

Follow the [shinyapps.io user guide](https://docs.rstudio.com/shinyapps.io/index.html) to set up your account and configure `rsconnect`.

Next, run the `deploy_labs()` function, which will send each lab to your Shiny server. By default, all labs are deployed, but you can specify which ones by providing the function with a vector of lab numbers, e.g. `deploy_labs(labvec = c(2,5))` will deploy only labs 2 and 5. 
The labs will be on shinyapps.io at URLs like this one : `https://YOURACCOUNTNAME.shinyapps.io/lab1/` etc.


## Contributing to the package

The package is on GitHub and you can use the usual GitHub process to file bug reports, send feature requests, contribute updates and bug fixes, etc. If you have any comments or feedback, I very much welcome them. Please file a [GitHub issue](https://github.com/andreashandel/iblir/issues) and let me know what you think.


## Further information

See the [package website](https://andreashandel.github.io/iblir/) for useful additional information.


## Contributors

The main content of this package was developed by [Brian McKay](https://brianmckay.netlify.app/). The package is maintained by [Brian McKay](https://brianmckay.netlify.app/) and [Andreas Handel](https://www.andreashandel.com/). A full list of contributors and a Bibtex entry for the citation [can be found here](https://andreashandel.github.io/iblir/authors.html).



## References
